---
abstract: 'Retrieve, drawing and printing database schema'
author:
  - 'Milan Sorm (sorm@milansorm.cz)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SchemaView-Plus
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 1.12
  Data::CompactDump: 0
  FindBin: 0
  Math::Project: 0
  Tk: 800.014
  Tk::FontDialog: 0
  Tk::MListbox: 0
  Tk::ProgressBar: 0
  XML::Dumper: 0.4
  XML::Parser: 0
version: 0.17
